// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GitInsightContext))]
    partial class GitInsightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("Infrastructure.Entities.CommitEntity", b =>
                {
                    b.Property<string>("RID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("RID", "CID");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Infrastructure.Entities.RepositoryEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommitSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
